--- 
tags: 
- hashpage
- gdoc
origin: git://github.com/hashpage/hpw-gdoc.git
description: Presents published Google document. A great way how to write content for your site.
home: http://github.com/hashpage/hpw-gdoc
